             set "arrowUp1=      .      "
             set "arrowUp2=    .:;:.    "
             set "arrowUp3=  .:;;;;;:.  "
             set "arrowUp4=    ;;;;;    "
             set "arrowUp5=    ;;;;;    "
             set "arrowUp6=    ;;;;;    "
            
           set "arrowDown1=    ;;;;;    "
           set "arrowDown2=    ;;;;;    "
           set "arrowDown3=    ;;;;;    "
           set "arrowDown4=  ..;;;;;..  "
           set "arrowDown5=   ':::::'   "
           set "arrowDown6=     ':`     "

           set "arrowLeft1=     .       "
           set "arrowLeft2=   .;;...... "
           set "arrowLeft3= .;;;;:::::: "
           set "arrowLeft4=  ':;;:::::: "
           set "arrowLeft5=    ':       "
           set "arrowLeft6=             "

          set "arrowRight1=       .     "
          set "arrowRight2= ......;;.   "
          set "arrowRight3= ::::::;;;;. "
          set "arrowRight4= ::::::;;:'  "
          set "arrowRight5=       :'    "
          set "arrowRight6=             "